### ISSUE TITLE
Linked List Operations in C++ 

### ISSUE THREAD

**Issue by vishnubansal001** [harsh9539/linkedlist#15]
Greetings! I'd like to contribute to this repository for Hacktoberfest 2023 by adding a C++ file containing code for creating a linked list and implementing essential functions. This addition aims to provide a clear and concise demonstration of linked list operations, making it a valuable resource for learners and enthusiasts alike. Let's collaborate to enhance the educational content of this repository!

**Comment by rv1830** [comment]
please assign me this would like to work  on this
