### ISSUE TITLE
feature: add reverse linked list function

### ISSUE THREAD

**Issue by harsh9539** [harsh9539/linkedlist#4]
Please provide a reverse linked list function with proper TC and SC.

**Comment by Kundanika04** [comment]
Could you assign this task to me?

**Comment by resilient-maximus** [comment]
@harsh9539 Since this is not yet resolved can you assign it to me?

**Comment by ShrutiShrivastava0613** [comment]
Added a pull request for this issue. Please check and merge request if no issues found.
